### ISSUE TITLE
Exception when closing on OS X

### ISSUE THREAD

**Issue by bobbylight** [bobbylight/RText#21]
Makes it so you cannot close the application!

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.fife.rtext.plugins.langsupport.Plugin.savePreferences(Plugin.java:649)
	at org.fife.rtext.RText.savePreferences(RText.java:1192)
	at org.fife.rtext.RText.doExit(RText.java:449)
	at org.fife.ui.app.AbstractGUIApplication.processWindowEvent(AbstractGUIApplication.java:1006)
	at java.awt.Window.processEvent(Window.java:2013)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
```

**Comment by bobbylight** [comment]
This was fixed in commit 6ef614941ec099f4a8617ace4bed790b6324098a.
