### ISSUE TITLE
NPE on save when user cancels Options dialog after changing app theme

### ISSUE THREAD

**Issue by bobbylight** [bobbylight/RText#48]
To reproduce:

1. Edit -> Options
2. User Interface panel -> select a new theme and click "Apply"
3. Click "Cancel" to close the Options dialog (not OK or its Apply button)
4. Close RText

Expected behavior:
"Apply" for the theme is a special button that applies all new theme state and doesn't trigger errors even if the overall theme changes are cancelled.

Actual behavior:
An NPE is triggered and RText doesn't close.

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at org.fife.rtext.RTextPrefs.save(RTextPrefs.java:620)
        at org.fife.rtext.RText.savePreferences(RText.java:1192)
        at org.fife.rtext.RText.doExit(RText.java:452)
        at org.fife.ui.app.AbstractGUIApplication.processWindowEvent(AbstractGUIApplication.java:983)
        at java.desktop/java.awt.Window.processEvent(Window.java:2037)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
```

**Comment by bobbylight** [comment]
Fixed with commit 744f231a2fc0c1c4fbdfdda629b2389a8de02163.
